# -*- coding: utf-8 -*-
"""age_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vvDDnCMr-ag7zC-VK-N4LiBsecvR-I_
"""

import datetime
print("===AGE CALCULATOR===")
current = datetime.datetime.now()
birth_year = int(input("What is your birthyear? "))
age = current.year - birth_year
print(f"You are {age} years old.")