# -*- coding: utf-8 -*-
"""clock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5hoQtZF-BNxQydlRNtvYlLwGzqVgu7q
"""

import datetime
print("===Digital Clock===")
current = datetime.datetime.now()
print(f"current time: {current.hour}:{current.minute}:{current.second}")