# -*- coding: utf-8 -*-
"""conditional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183ZrQ3vKCrtqNcTrxV4AUeLunaPV93iH
"""

print("=====WELCOME=====")
print("choose one of them ")
print("1. want to be rich? ")
print("2. want to get married")
print("3. Rich + Family ")
while True:
  a = input("Enter a number 1, 2 or 3: ")
  if a in("1", "2", "3"):
    break
if a=="1":
  print("Nice! ")
elif a=="2":
  print("be successful before marriage. ")
elif a=="3":
  print("Good ")