# -*- coding: utf-8 -*-
"""full_year_calendar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7Y888ZtCK1wXAf0cs9K6yovDhNa0VFJ
"""

import calendar
while True:
  year = input("Which year's calendar would you like to see? ")
  if year.isdigit():
    year = int(year)

    print(calendar.calendar(year))
    break
  else:
    print("Please enter a valid year (numbers only). ")