# -*- coding: utf-8 -*-
"""guessing_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L78R1tKYpmSHZBhOxxBYVEccvd52382v
"""

import random
number = random.randint(1, 10)
tries = int(input("How many attempts do you need to guess the number? "))
attempts = 0
while attempts < tries:
  print("====Guessing game====")
  number = int(input("Enter a number betweeen 1, 10: "))
  attempts += 1
  if number < tries:
    print("Too Low.")
  elif number >= tries:
    print("Too high.")
  elif number == tries:
    print("Congratulations!")
    break
  else:
    continue
  print("attempts", attempts, "done.")