# -*- coding: utf-8 -*-
"""RPS_Battle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gctc035kAgwCAxVKD8ISoO8oZ4UVE9qN
"""

import random
user_score = 0
computer_score = 0
tie = 0
choices = {
    1: "Rock",
    2: "Paper",
    3: "Scissors"
    }
while True:
  print("\n====Rock Paper Scissors Game====")

  print("\n1. Rock \n2. Paper \n3. Scissors")

  try:
    user_choice = int(input("Enter your choice: "))
    if user_choice not in [1, 2, 3]:
      print("Invalid choice. Please try again.")
      continue
  except ValueError:
    print("Invalid input. Please enter a number.")
    continue
  computer = random.randint(1,3)
  print("\nYou chose: ", choices[user_choice])
  print("\nComputer chose: ", choices,[computer])

  if user_choice == computer:
    print("It's a Tie.")
    tie += 1

  elif(user_choice == 1 and computer == 3) or \
  (user_choice == 2 and computer == 1) or\
  (user_choice == 3 and computer == 2):
  print("You win!")
  user_score += 1
  else:
    print("Computer win!")
    computer_score += 1
  print("\n----Score---- ")
  print("Your score: ", user_score)
  print("Computer score: ", computer_score)
  print("Tie: ",tie)
  while True:
    again = input("\nDo you want to play again (yes/no): ").lower()
    if again == "yes":
      break
    elif again == "no":
      print("Thanks for playing.")
      exit()
    else:
      print("say only yes or no.")