# -*- coding: utf-8 -*-
"""table_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133DgR3vJXdud4KPxmUiD-6rxcGIZ_rzV
"""

while True:
  print("====TABLE GENERATOR====")
  number = int(input("Enter a number: "))
  for i in range(1, 11):
    print(number, "X", i, "=", number*i)
  again = input("Do you want to generate another table? ").lower()
  if again == "no":
    print("Thank you. ")
    break
  else:
    continue