# -*- coding: utf-8 -*-
"""vowel_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cc9x1JpxFafnIkmcgr85pU4GeMchtwQF
"""

while True:
  ask = input("Do you want to check if letter is vowel or consonant? ").lower()
  if ask == "no":
    break
  elif ask != "yes":
    print("Enter only yes or no: ")
    continue
  print("====VOWEL CHECKER====")
  letter = input("Enter a letter: ").lower()
  if len(letter) !=1 or not  letter.isalpha():
    print("INVALID INPUT")
  elif letter in ("aeiou"):
    print(f"{letter} is a vowel. ")
  else:
    print(f"{letter} is consonant")
  again = input("Do you want to check again? ").lower()
  if again in ("yes"):
    continue
  elif again in ("no"):
    break
  else:
    notvalid = input("Enter only yes or no: ")
    if notvalid in ("yes"):
      continue#
    elif notvalid in ("no"):
      print("THANKS.")
      break
    else:
      print("Program crashed.")